// 2022.11.1-SR-W44-c2fWuH-瀚元科技-下拉查询-bigscreen-react-plugin/src/App.js
import React from "react";
import {
  DataConfiguration,
  StyleConfiguration,
  OtherConfiguration,
  MainRender
} from "./components";
import PropTypes from "prop-types";
import Main from "./components/main";

const renderHashMap = {
  Main: MainRender,
  dataConfiguration: DataConfiguration,
  styleConfiguration: StyleConfiguration,
  otherConfiguration: OtherConfiguration
};
const App = ({ type, mode, ...props }) => {
  if (mode === "development") {
    let handleConfiguration = () => {
      console.log("configuration has changed");
    };
    let handleOptionsChange = () => {
      return "configureation";
    };
    const options = {
      changeConfiguration: handleOptionsChange,
      configuration: handleConfiguration(),
      ...props
    };
    return (
      <>
        <div id={"main"}>
          <div className="left">主视图</div>
          <div className="right" style={{ width: "90%", height: "400px" }}>
            <Main {...props}></Main>
          </div>
        </div>
        <div id={"style"}>
          <div className="left">style</div>
          <div className="right">
            <StyleConfiguration {...options}></StyleConfiguration>
          </div>
        </div>
        <div id={"data"}>
          <div className="left">data</div>
          <div className="right">
            <DataConfiguration {...options}></DataConfiguration>
          </div>
        </div>
        <div id={"other"}>
          <div className="left">other</div>
          <div className="right">
            <OtherConfiguration {...options}></OtherConfiguration>
          </div>
        </div>
      </>
    );
  } else {
    let handleConfiguration = () => {
      const { block } = props;
      const { dataConfig } = block;
      const { pluginOptions = {}, columns } = dataConfig;
      pluginOptions.columns = columns;
      return pluginOptions;
    };
    //处理配置更新
    let handleOptionsChange = (pluginOptions) => {
      const {
        bigscreen: { updateBlockById, pluginDetailMap },
        block: {
          baseConfig: { id }
        }
      } = props;
      updateBlockById(id, { dataConfig: { pluginOptions: { ...pluginOptions } } });
      //调用加载器的run方法强制更新
      pluginDetailMap[`${id}-default`].detail.ref.current.run();
    };
    if (!type) {
      return (<Main {...props}></Main>);
    } else {
      const options = {
        changeConfiguration: handleOptionsChange,
        configuration: handleConfiguration(),
        ...props
      };
      let Comp = () => <></>;
      if (renderHashMap[type]) Comp = renderHashMap[type];
      return <Comp {...options} />;
    }
  }
};


App.propTypes = {
  type: PropTypes.string
};

export default App;

// 2022.12.19-SR-W50-YxtN3m-单元格合并的定制化表格-宁杭大脑-合并单元格-bigscreen-vue-plugin/src/App.vue
<script>
import {
  DataConfiguration,
  StyleConfiguration,
  OtherConfiguration,
  Main
} from "./components";

export default {
  name: "App",
  components: { StyleConfiguration, DataConfiguration, OtherConfiguration, Main },
  props: {
    componentId: String,
    options: {
      type: Object,
      default: () => ({
        // 配置项从externalVariables里取
        externalVariables: {}
      })
    },
    block: Object,
    bigscreen: Object,
    notifyVariable: Function,
    type: String,
    pubSub: Object,
    eventBus: Object,
    data: Object | Array,
    updateProcess: Function
  },
  data() {
    return {};
  },
  computed: {},
  watch: {},
  created() {
  },
  mounted() {
  },
  beforeDestroy() {
  },
  methods: {},
  render(h) {
    let props = this._props;
    let handleConfiguration = () => {
      const dataConfig = props.block?.dataConfig || {};
      const { pluginOptions = {}, columns } = dataConfig;
      pluginOptions.columns = columns;
      return pluginOptions;
    };
    let changeConfiguration = (pluginOptions) => {
      if (props.bigscreen && props.block) {
        const {
          bigscreen: { updateBlockById, pluginDetailMap },
          block: {
            baseConfig: { id }
          }
        } = props;
        updateBlockById(id, { dataConfig: { pluginOptions: { ...pluginOptions } } });
        pluginDetailMap[`${id}-default`].detail.ref.current.run();
      } else {
        console.log("暂时无此方法，请升级版本");
      }
    };
    props = { configuration: handleConfiguration(), ...props };
    if (!this.type) {
      return <Main {...{ props }} />;
    } else {
      const renderhMap = {
        dataConfiguration: DataConfiguration,
        styleConfiguration: StyleConfiguration,
        otherConfiguration: OtherConfiguration
      };
      const Comp = renderhMap[this.type];
      props = { configuration: handleConfiguration(), changeConfiguration, ...props };
      return (
        <Comp {...{ props }} />
      );

    }

  }
};
</script>
