// 2022.11.1-SR-W44-c2fWuH-瀚元科技-下拉查询-bigscreen-react-plugin/src/App.js
import React from "react";
import {
  DataConfiguration,
  StyleConfiguration,
  OtherConfiguration,
  MainRender
} from "./components";
import PropTypes from "prop-types";
import Main from "./components/main";

const renderHashMap = {
  Main: MainRender,
  dataConfiguration: DataConfiguration,
  styleConfiguration: StyleConfiguration,
  otherConfiguration: OtherConfiguration
};
const App = ({ type, mode, ...props }) => {
  if (mode === "development") {
    let handleConfiguration = () => {
      console.log("configuration has changed");
    };
    let handleOptionsChange = () => {
      return "configureation";
    };
    const options = {
      changeConfiguration: handleOptionsChange,
      configuration: handleConfiguration(),
      ...props
    };
    return (
      <>
        <div id={"main"}>
          <div className="left">主视图</div>
          <div className="right" style={{ width: "90%", height: "400px" }}>
            <Main {...props}></Main>
          </div>
        </div>
        <div id={"style"}>
          <div className="left">style</div>
          <div className="right">
            <StyleConfiguration {...options}></StyleConfiguration>
          </div>
        </div>
        <div id={"data"}>
          <div className="left">data</div>
          <div className="right">
            <DataConfiguration {...options}></DataConfiguration>
          </div>
        </div>
        <div id={"other"}>
          <div className="left">other</div>
          <div className="right">
            <OtherConfiguration {...options}></OtherConfiguration>
          </div>
        </div>
      </>
    );
  } else {
    let handleConfiguration = () => {
      const { block } = props;
      const { dataConfig } = block;
      const { pluginOptions = {}, columns } = dataConfig;
      pluginOptions.columns = columns;
      return pluginOptions;
    };
    //处理配置更新
    let handleOptionsChange = (pluginOptions) => {
      const {
        bigscreen: { updateBlockById, pluginDetailMap },
        block: {
          baseConfig: { id }
        }
      } = props;
      updateBlockById(id, { dataConfig: { pluginOptions: { ...pluginOptions } } });
      //调用加载器的run方法强制更新
      pluginDetailMap[`${id}-default`].detail.ref.current.run();
    };
    if (!type) {
      return (<Main {...props}></Main>);
    } else {
      const options = {
        changeConfiguration: handleOptionsChange,
        configuration: handleConfiguration(),
        ...props
      };
      let Comp = () => <></>;
      if (renderHashMap[type]) Comp = renderHashMap[type];
      return <Comp {...options} />;
    }
  }
};


App.propTypes = {
  type: PropTypes.string
};

export default App;

// 2022.11.7-SR-W45-f1nC6L-瀚元科技大屏/瀚元防御结果分时统计大屏-vue/src/App.vue
<script>
import {
  DataConfiguration,
  StyleConfiguration,
  OtherConfiguration,
  Main
} from "./components";
import mockData from "./mockData.js";

export default {
  name: "App",
  components: { StyleConfiguration, DataConfiguration, OtherConfiguration, Main },
  props: {
    componentId: String,
    eventBus: Object,
    options: {
      type: Object,
      default: () => ({
        // 配置项从externalVariables里取
        externalVariables: {}
      })
    },
    block: Object,
    bigscreen: Object,
    notifyVariable: Function,
    type: String,
    mode: String,
    pubSub: Object,
    variable: Object
  },
  data() {
    return {};
  },
  computed: {},
  watch: {},
  created() {
    this.eventBus?.on((newProps) => {
      for (const newPropsKey in newProps) {
        this[newPropsKey] = newProps[newPropsKey];
      }
    });
  },
  mounted() {
  },
  beforeDestroy() {
    this.eventBus?.remove();
  },
  methods: {
    Event_Center_getName: () => {
      return this.id;
    }
  },
  render(h) {
    if (this.mode === "development") {
      let props = mockData;
      return (
        <div>
          <div id={"main"}>
            <div class="left">主视图</div>
            <div class="right" style={{ height: "900px" }}>
              <Main {...{ props }}></Main>
            </div>
          </div>
          <div id={"style"}>
            <div class="left">style</div>
            <div class="right">
              <StyleConfiguration {...{ props }} />
            </div>
          </div>
          <div id={"data"}>
            <div class="left">data</div>
            <div class="right">
              <DataConfiguration {...{ props }} />
            </div>
          </div>
          <div id={"other"}>
            <div class="left">other</div>
            <div class="right">
              <OtherConfiguration {...{ props }} />
            </div>
          </div>
        </div>
      );
    } else {
      let props = this._props;
      let handleConfiguration = () => {
        const { block } = props;
        const { dataConfig } = block;
        const { pluginOptions = {}, columns } = dataConfig;
        pluginOptions.columns = columns;
        return pluginOptions;
      };
      let changeConfiguration = (pluginOptions) => {
        const {
          bigscreen: { updateBlockById, pluginDetailMap },
          block: {
            baseConfig: { id }
          }
        } = props;
        updateBlockById(id, { dataConfig: { pluginOptions: { ...pluginOptions } } });
        pluginDetailMap[`${id}-default`].detail.ref.current.run();
      };
      props = { configuration: handleConfiguration(), ...props };
      if (!this.type) {
        return <Main {...{ props }} />;
      } else {
        const renderHashMap = {
          dataConfiguration: DataConfiguration,
          styleConfiguration: StyleConfiguration,
          otherConfiguration: OtherConfiguration
        };
        const Comp = renderHashMap[this.type];
        props = { configuration: handleConfiguration(), changeConfiguration, ...props };
        return (
          <Comp {...{ props }} />
        );

      }
    }

  }
};
</script>
